name: steam_games_analytics
version: 1.0.0
config-version: 2

profile: steam_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  steam_games_analytics:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
